project:
  type: website

website:
  title: "AMMnet Hackathon"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AMMnet/ammnet-hackathon
      - icon: twitter
        href: https://x.com/AMMnetwork

format:
  html:
    theme:
    - flatly
    - custom.scss

execute:
  freeze: auto


