project:
  type: website

website:
  title: "AMMnet Hackathon"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AMMnet/ammnet-hackathon
      - icon: twitter
        href: https://x.com/AMMnetwork
  google-analytics: "G-072Z4G50DN"

format:
  html:
    theme:
    - flatly
    - custom.scss
    comments:
      utterances:
         repo: AMMnet/ammnet-hackathon

execute:
  freeze: auto


